# Generated by Django 3.2.6 on 2021-10-30 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_author_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='body',
            new_name='description',
        ),
    ]
