# Generated by Django 3.2.6 on 2021-10-30 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
