# Generated by Django 3.2.6 on 2021-10-31 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20211030_0833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='first_published@',
            new_name='last_updated',
        ),
    ]
