# Generated by Django 4.0.5 on 2022-08-15 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='owner',
            field=models.OneToOneField(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='authorsetting',
            name='owner',
            field=models.OneToOneField(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to='user.author'),
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='owner',
            field=models.OneToOneField(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
